#!/bin/sh
export HISTFILE=$HOME/.config/zsh/history
export HISTSIZE=100000
export SAVEHIST=100000
export PATH="$HOME/.local/bin":$PATH
export MANPAGER='lvim +Man!'
export MANWIDTH=999
export PATH=$HOME/.cargo/bin:$PATH
export PATH=$HOME/.local/share/go/bin:$PATH
export GOPATH=$HOME/.local/share/go
export PATH=/home/dev/.config/npm:$PATH
export PATH=$HOME/.fnm:$PATH
# eval "`fnm env`"

# eval "$(fnm env)"
eval "$(zoxide init zsh)"
# eval "`pip completion --zsh`"

export NNN_PLUG='o:fzopen;m:nmount;x:!chmod +x $nnn'
export LC_COLLATE="C"

# for psql docker
export UID=$(id -u)
export GID=$(id -g)

export ANDROID_SDK_ROOT=$HOME/Android/Sdk
export PATH=$PATH:$ANDROID_SDK_ROOT/emulator
export PATH=$PATH:$ANDROID_SDK_ROOT/platform-tools
export PATH=$PATH:$ANDROID_SDK_ROOT/tools
export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
# __conda_setup="$("$HOME/.miniconda/bin/conda" 'shell.zsh' 'hook' 2> /dev/null)"
# if [ $? -eq 0 ]; then
#     eval "$__conda_setup"
# else
#     if [ -f "$HOME/.miniconda/etc/profile.d/conda.sh" ]; then
#         . "$HOME/.miniconda/etc/profile.d/conda.sh"
#     else
#         export PATH="$HOME/.miniconda/bin:$PATH"
#     fi
# fi
# unset __conda_setup
# <<< conda initialize <<<

autoload -U +X compinit && compinit

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
